### ISSUE TITLE
how to plot values between -pi and pi？

### ISSUE THREAD

**Issue by songhat** [circstat/pycircstat2#8]
like this
![image](https://github.com/circstat/pycircstat2/assets/48643755/7682ca32-2a9d-4f59-a73a-7d968207d925)

**Comment by huangziwei** [comment]
We perform all calculations in the range [0,2π) to maintain consistency with most textbooks. We have a helper function called `angrange()` in the utils module to transform the data accordingly. Regarding your question about plotting, you can simply change the labels from [π,2π) to [±π,0). We have many examples in the example notebooks that change labels, you can check them out.
